### ISSUE TITLE
Use multi select options in Tabular view

### ISSUE THREAD

**Issue by andresgutgon** [EcoLogicAG/datocms-plugin-multiselect#1]
# What?
Hi, first of all thanks for the plugin. It works nice as far I can tell. I just starting testing if we can use it. There are a couple of things I not sure I fully understand.

- Tabular view multiselect field as column
- Default value

## Our use case
We want to add a multi select option to our Dato to allow editors tell in what countries we want a page visible.

## Tabular view multiselect field as column
I added the plugin and selected the field `countries` as a header in `Tabular view`. But the the actual value is not displayed just the world `json`
![image](https://user-images.githubusercontent.com/49499/53403038-25588c00-39b3-11e9-8729-7af9c0aca2a2.png)

## Default value
I wanted all previous pages to have a default value. I added it to plugin config like this:
![image](https://user-images.githubusercontent.com/49499/53403204-7c5e6100-39b3-11e9-9433-37159f190b45.png)
But this doesn't set that value as `default` on new records, neither fill it previous records with that default value. Is that normal?

**Comment by magbeat** [comment]
Hi @andresgutgon 

Thanks for asking. It seems that you are trying to add the values in the "wrong tab". Can you try and put them into Presentation -> Field Editor Options:

![image](https://user-images.githubusercontent.com/1089410/53428001-41c3eb00-39ea-11e9-9348-3589c374838e.png)

**Comment by andresgutgon** [comment]
No I just did that
![image](https://user-images.githubusercontent.com/49499/53436344-4e047400-39fb-11e9-8f09-613b6742c03e.png)


I was asking for a `default option` enabled for:
1. Existing pages (I guest this is imposible without a data migration)
2. New page. Here I would like to see a `default` checked something like this:
![image](https://user-images.githubusercontent.com/49499/53436461-8ad06b00-39fb-11e9-9332-c100018a7904.png)

**Comment by magbeat** [comment]
I guess this is only possible with a data migration. We added a DatoCMS boolean field recently and we had to update the "default" value for the existing records via the Management API.

Ah, yes. Let me fix this ;)

**Comment by magbeat** [comment]
Well, just looked at the code and the documentation. It was actually intended in this way: store the `key`, display the `value`. If its ok with you.

**Comment by magbeat** [comment]
For the update part. I have extracted the essence of our scripts to a seperate  repository. Maybe the scripts can be of some help to you: https://github.com/EcoLogicAG/dato-cms-scripts
