### ISSUE TITLE
Single select

### ISSUE THREAD

**Issue by jesperkc** [EcoLogicAG/datocms-plugin-multiselect#2]
Thank you for a great plugin.

Even though it contradicts the plugin name, would it be possible to add an option to allow only a single selection? Like radio buttons.

**Comment by magbeat** [comment]
Hi @jesperkc 
Isn't https://www.datocms.com/marketplace/plugins/i/@dynvis/datocms-plugin-typed-list what you need?

**Comment by jesperkc** [comment]
Hi @magbeat 
I looked at that plugin but it's not really what I need. 
Ideally I need a select/radio-list for selecting between predefined values in a Dato component. And the closest thing I could find was this component.

**Comment by magbeat** [comment]
Hi @jesperkc 
I made a quick fork and had a look at it. How would you store the value? I guess you have an array of options in the plugin settings and then store the selected key in a text value of the model. Right?

**Comment by magbeat** [comment]
Hi @jesperkc 
I guess you could use the validation field in the model editor, like that:

![image](https://user-images.githubusercontent.com/1089410/83519349-175db900-a4dc-11ea-9d23-8c12895c50f9.png)

**Comment by jesperkc** [comment]
> Hi @jesperkc
> I made a quick fork and had a look at it. How would you store the value? I guess you would have an array of options in the plugin settings and then store the selected key in a text value of the model. Right?

Hi

Yeah, it's basically "just" a UI issue. I would still setup the component and store the selected value the same way as now. But the CMS user should only be able to select one option instead of multiple

**Comment by magbeat** [comment]
Hi @jesperkc 
have you looked at the `Accept only specified values` option? It generates a select with the options provided:

![image](https://user-images.githubusercontent.com/1089410/83536052-0a988f80-a4f3-11ea-81d6-c7a035bcfdc5.png)
